# Generated by Django 6.0.6 on 2026-06-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
